Repository cubefs/cubefs, pull requests merged in 2020-09, with the labels that each got.

#870 Fix: no such bucket when create bucket using S3 API
  objectnode/auth_signature_v2.go
  objectnode/auth_signature_v4.go
Labels: priority/high

#865 Update ADOPTERS.md
  ADOPTERS.md
Labels: documentation

#891 Update CHANGELOG.md for v2.2.0
  CHANGELOG.md
Labels: documentation, enhancement, priority/normal

#898 Makes release note of version v2.2.1 more readable.
  CHANGELOG.md
Labels: documentation, enhancement

#897 Replaced Chinese content to English from EN documentation.
  docs/source/csv/performance-volume.csv
Labels: documentation

#901 Fix the issue that recursive making directory concurrent with sample multi-layer path prefix.
  objectnode/fs_volume.go
Labels: DO NOT MERGE, bug, component/objectnode, interface/s3, priority/high

#906 Add configuration to enable POSIX ACL for client
  client/fuse.go
  proto/mount_options.go
  vendor/bazil.org/fuse/fuse_kernel.go
  vendor/bazil.org/fuse/options.go
Labels: priority/high, security

#939 Update CHANGELOG.md for v2.2.2
  CHANGELOG.md
Labels: documentation

#953 Fix: key encoding issue of S3 ListObjects API.
  objectnode/api_handler_object.go
  objectnode/const.go
  objectnode/etag.go
  objectnode/fs_store_user.go
  objectnode/fs_volume.go
  objectnode/util.go
Labels: interface/s3
