Repository cubefs/cubefs, pull requests merged in 2020-07, with the labels that each got.

#711 Refactor：remove repeated and useless checks,and expand the scope of the lock
  metanode/manager.go
Labels: enhancement, priority/normal

#714 Update ADOPTERS.md
  ADOPTERS.md
Labels: documentation

#713 Enhancement: Reset raft peers of DataNode & MetaNode.
  cli/cmd/datanode.go
  cli/cmd/datapartition.go
  cli/cmd/metanode.go
  cli/cmd/metapartition.go
  datanode/const.go
  datanode/partition.go
  datanode/partition_raft.go
  datanode/wrap_operator.go
  docker/script/start_client.sh
  master/api_service.go
  master/api_service_test.go
  master/cluster.go
  master/cluster_task.go
  master/data_partition.go
  master/http_server.go
  master/meta_partition.go
  master/mocktest/data_server.go
  master/mocktest/meta_server.go
  master/operate_util.go
  metanode/manager.go
  metanode/manager_op.go
  metanode/partition.go
  metanode/partition_fsmop.go
  proto/admin_proto.go
  proto/errors.go
  proto/packet.go
  raftstore/partition.go
  sdk/master/api_admin.go
  vendor/github.com/tiglabs/raft/README.md
  vendor/github.com/tiglabs/raft/errors.go
  vendor/github.com/tiglabs/raft/proto/proto.go
  vendor/github.com/tiglabs/raft/raft_fsm.go
  vendor/github.com/tiglabs/raft/server.go
Labels: enhancement

#724 Parallel offline partition
  master/cluster.go
  master/cluster_task.go
  master/config.go
  master/data_partition_check.go
  master/meta_partition.go
  master/vol.go
Labels: enhancement, priority/normal

#730 Fix: S3 response when volume do not exists
  objectnode/api_middleware.go
  objectnode/auth_signature_v2.go
  objectnode/auth_signature_v4.go
  objectnode/auth_signature_v4_test.go
  objectnode/policy.go
  sdk/meta/meta.go
Labels: bug, interface/s3, priority/high

#726 Enhancement: add administration API for node info collection
  cmd/master/scripts/manage_admin_getnodeinfo.sh
  cmd/master/scripts/manage_admin_setnodeinfo.sh
  cmd/master/scripts/manage_mn_get_params.sh
  cmd/master/scripts/manage_mn_set_params.sh
  datanode/nodeinfo.go
  datanode/partition.go
  datanode/server.go
  datanode/wrap_operator.go
  docs/source/admin-api/master/cluster.rst
  master/api_service.go
  master/cluster.go
  master/config.go
  master/const.go
  master/data_node.go
  master/http_server.go
  master/meta_node.go
  master/metadata_fsm_op.go
  metanode/manager.go
  metanode/manager_op.go
  metanode/metanode.go
  metanode/nodeinfo.go
  metanode/partition_free_list.go
  proto/admin_proto.go
  proto/packet.go
  storage/extent_store.go
Labels: enhancement, priority/normal

#729 refactor: whether to cache volume oss meta is determined by the configuration parameter 'strict'
  docker/s3tests/base.py
  docker/s3tests/test_cors.py
  objectnode/acl.go
  objectnode/acl_handler.go
  objectnode/api_middleware.go
  objectnode/cors_handler.go
  objectnode/fs_manager.go
  objectnode/fs_volume.go
  objectnode/fs_volume_meta.go
  objectnode/policy.go
  objectnode/policy_handler.go
  objectnode/server.go
Labels: component/objectnode, enhancement, interface/s3, priority/normal

#736 Fix: ListBuckets and headBucket result is empty using java sdk
  objectnode/api_handler_bucket.go
  objectnode/const.go
Labels: bug, interface/s3, priority/high

#738 Fix: putObject the key with double slash return 403
  objectnode/auth_signature_v4.go
Labels: bug, interface/s3, priority/normal

#739 Refactor: using path style when signurl by console
  console/service/file.go
  docker/conf/nginx.conf
Labels: enhancement

#701 Update CHANGELOG from v2.0.0 to v2.1.0
  CHANGELOG.md
Labels: DO NOT MERGE

#749 Fix: some bugs about object tagging and bucket tagging
  objectnode/api_handler_bucket.go
  objectnode/api_handler_object.go
  objectnode/const.go
  objectnode/fs_store_xattr.go
  objectnode/fs_volume.go
  objectnode/result.go
  objectnode/result_error.go
Labels: bug, component/objectnode, priority/normal

#752 Update: update docker grafana data size unit from IEC to Metric
  docker/monitor/grafana/provisioning/dashboards/chubaofs.json
Labels: enhancement, priority/normal

#757 Enhancement: Add objectnode api 'deleteBucketPolicy' and related test cases
  docker/s3tests/base.py
  docker/s3tests/test_acl.py
  docker/s3tests/test_bucket_policy.py
  objectnode/acl.go
  objectnode/acl_handler.go
  objectnode/policy.go
  objectnode/policy_handler.go
  objectnode/stringset.go
Labels: component/objectnode, enhancement, interface/s3

#765 Enhancement: unified version information
  build/build.sh
  cli/build.sh
  cli/cmd/root.go
  client/build.sh
  client/fuse.go
  cmd/build.sh
  cmd/cmd.go
  proto/version.go
Labels: enhancement, priority/normal

#769 Fix: listObjects and listObjectsV2 list result is not expected
  objectnode/fs.go
  objectnode/fs_volume.go
Labels: bug, component/objectnode, interface/s3, priority/normal

#770 Enhancement: add zonename flag to cli tool
  cli/cmd/const.go
  cli/cmd/vol.go
  sdk/master/api_admin.go
Labels: component/cli, enhancement

#772 Update ADOPTERS.md
  ADOPTERS.md
Labels: documentation

#773 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation

#780 Enhancement: add ump monitor log
  objectnode/api_context.go
  objectnode/api_middleware.go
  objectnode/result_error.go
Labels: component/objectnode, enhancement

#779 Support direct compile or docker cross compile on Arm64 ,pass under Ubuntu 14.04 and CentOS7.6
  .gitignore
  README.md
  build.sh
  build/build.sh
  build/compile/arm64/Dockerfile
  build/compile/arm64/buildcfs.sh
  build/compile/arm64/centos/Dockerfile
  build/compile/arm64/centos/buildcfs.sh
  build/compile/arm64/gcc4/Dockerfile
  build/compile/arm64/gcc4/buildcfs.sh
Labels: enhancement

#782 Add security disclosure process
  README.md
  security/README.md
  security/email-templates.md
  security/security-release-process.md
Labels: cncf, documentation, priority/high

#784 Fix: issue of update etag when list files
  objectnode/fs_volume.go
Labels: bug, interface/s3, priority/high

#785 Fix: fix metanode delete dentry deadlock bug
  metanode/partition.go
  metanode/partition_fsmop_dentry.go
Labels: bug, priority/high

#781 Refactor: optimize delete Extent on metanode and datanode
  datanode/const.go
  datanode/data_partition_repair.go
  datanode/limit.go
  datanode/nodeinfo.go
  master/api_service.go
  master/api_service_test.go
  master/cluster.go
  master/config.go
  master/const.go
  master/data_node.go
  master/data_partition.go
  master/data_partition_check.go
  master/meta_node.go
  master/meta_node_test.go
  master/meta_partition.go
  master/meta_partition_manager.go
  master/metadata_fsm_op.go
  master/node_selector.go
  master/operate_util.go
  master/token.go
  master/vol_test.go
  metanode/free_list.go
  metanode/partition_delete_extents.go
  metanode/partition_free_list.go
  metanode/partition_fsmop.go
  metanode/partition_op_multipart.go
  metanode/raft_server.go
  proto/admin_proto.go
  proto/extent_key.go
  proto/model.go
  proto/packet.go
  repl/packet.go
  repl/repl_protocol.go
Labels: enhancement, priority/high

#791 Fix: main build script issue
  build/build.sh
Labels: bug, priority/high

#796 Fix: update etag issue when listing objects
  docker/s3tests/test_object_list.py
  objectnode/fs_volume.go
Labels: bug, priority/high

#798 Enhancement: add test for list objects v2 ETag validation
  docker/s3tests/test_object_list.py
Labels: enhancement
