Repository cubefs/cubefs, pull requests merged in 2020-03, with the labels that each got.

#398 Replaced Dup2 syscall with Dup3
  client/fuse.go
  clientv2/main.go
  cmd/cmd.go
Labels: enhancement

#400 Enhancement: add nginx and upstream for objectnode in docker compose
  docker/conf/nginx.conf
  docker/conf/objectnode.json
  docker/docker-compose.yml
Labels: enhancement

#401 Enhancement: adapt raft to more platform
  vendor/github.com/tiglabs/raft/util/log/log_crash_darwin.go
  vendor/github.com/tiglabs/raft/util/log/log_crash_linux.go
Labels: enhancement

#424 Fix: issue of expect result wile list objects
  master/server.go
  objectnode/fs_volume.go
Labels: bug, object-storage-interface

#428 Fix: issue on list objects with delimiter
  objectnode/fs_volume.go
  objectnode/result.go
Labels: bug, compatibility, object-storage-interface

#433 Fix empty result on list objects
  objectnode/api_handler_object.go
  objectnode/fs_volume.go
  objectnode/router.go
Labels: bug, compatibility, object-storage-interface

#434 Refactor the index of user store and user api
  cli/cmd/fmt.go
  cli/cmd/user.go
  client/fuse.go
  master/api_service.go
  master/api_service_user.go
  master/const.go
  master/http_server.go
  master/master_manager.go
  master/metadata_fsm.go
  master/metadata_fsm_op.go
  master/user.go
  master/userdata_fsm_op.go
  objectnode/api_handler_bucket.go
  objectnode/auth_signature_v2.go
  objectnode/auth_signature_v4.go
  objectnode/fs_store_user.go
  objectnode/fs_volume.go
  objectnode/policy.go
  objectnode/server.go
  proto/admin_proto.go
  proto/user_proto.go
  sdk/master/api_admin.go
  sdk/master/api_user.go
Labels: enhancement

#435 Enhancement: use tokens to distinguish read and write permissions for clients
  client/fs/super.go
  client/fuse.go
  clientv2/fs/super.go
  clientv2/main.go
  cmd/master/scripts/manage_token_add.sh
  cmd/master/scripts/manage_token_delete.sh
  cmd/master/scripts/manage_token_get.sh
  cmd/master/scripts/manage_token_update.sh
  cmd/master/scripts/manage_vol_create.sh
  cmd/master/scripts/manage_vol_update.sh
  master/api_service.go
  master/api_service_test.go
  master/cluster.go
  master/cluster_stat.go
  master/cluster_test.go
  master/const.go
  master/http_server.go
  master/master_manager.go
  master/metadata_fsm.go
  master/metadata_fsm_op.go
  master/token.go
  master/vol.go
  master/vol_test.go
  proto/admin_proto.go
  proto/errors.go
  proto/model.go
  proto/mount_options.go
  sdk/master/api_client.go
  sdk/meta/meta.go
  sdk/meta/view.go
Labels: authorization, enhancement, posix

#437 fix: set lookup valid duration for newly created file
  client/fs/dir.go
Labels: enhancement, posix

#439 docs: update FUSE client mount options
  docs/source/user-guide/client.rst
Labels: enhancement

#444 Fix: defective code in NewExtentClient method
  sdk/data/stream/extent_client.go
Labels: bug

#445 Enhancement: API and CLI command for update user information and delete user
  cli/cmd/user.go
  master/api_service.go
  master/api_service_user.go
  master/const.go
  master/http_server.go
  master/master_manager.go
  master/server.go
  master/user.go
  proto/admin_proto.go
  proto/errors.go
  proto/user_proto.go
  sdk/master/api_user.go
Labels: enhancement

#447 Enhancement: auto create user while create volume
  cli/cmd/vol.go
  docker/script/build.sh
  master/api_service.go
  master/api_service_user.go
  master/user.go
  proto/user_proto.go
Labels: enhancement

#449 feature: add token document
  docs/source/admin-api/master/volume.rst
Labels: priority/normal

#451 Fix: transfer vol failed when transfer to owner after creating owner
  master/user.go
Labels: bug, component/cli, component/master, priority/high

#450 Enhancement: folder operations in object storage interface
  objectnode/acl_handler.go
  objectnode/api_handler.go
  objectnode/api_handler_bucket.go
  objectnode/api_handler_multipart.go
  objectnode/api_handler_object.go
  objectnode/api_middleware.go
  objectnode/const.go
  objectnode/fs.go
  objectnode/fs_volume.go
  objectnode/policy.go
  objectnode/policy_handler.go
  objectnode/result.go
  objectnode/result_error.go
  objectnode/util.go
Labels: compatibility, component/objectnode, enhancement, interface/s3, priority/high

#453 many fixes and features
  client/fs/dir.go
  client/fs/super.go
  client/fuse.go
  proto/mount_options.go
  sdk/data/wrapper/wrapper.go
Labels: component/client, enhancement, priority/normal

#456 Fix:parse param 'part-number-marker' failed when listing parts of one…
  docker/conf/nginx.conf
  objectnode/api_handler_multipart.go
Labels: bug, compatibility, component/objectnode, enhancement, interface/s3, priority/normal

#457 feature: provide cluster space statistics API
  cmd/master/scripts/manage_cluster_stat.sh
  docs/source/admin-api/master/cluster.rst
  master/api_service.go
  master/api_service_test.go
  master/cluster.go
  master/cluster_stat.go
  master/http_server.go
  proto/admin_proto.go
  proto/model.go
Labels: component/master, enhancement, priority/normal

#458 Enhancement: reduce blocking under concurrency
  docker/conf/objectnode.json
  docker/docker-compose.yml
  objectnode/acl.go
  objectnode/api_handler.go
  objectnode/api_handler_bucket.go
  objectnode/fs_manager.go
  objectnode/fs_store_user.go
  objectnode/fs_store_xattr.go
  objectnode/fs_volume.go
  objectnode/policy.go
  objectnode/server.go
Labels: DO NOT MERGE, component/objectnode, enhancement, priority/normal
