Repository cubefs/cubefs, pull requests merged in 2023-03, with the labels that each got.

#1732 docs(docs-zh): update docs
  docs-zh/source/faq.rst
Labels: documentation

#1744 feat(rpc): set default rpc transport config
  blobstore/api/clustermgr/client.go
  blobstore/blobnode/shard_test.go
  blobstore/blobnode/worker_service_test.go
  blobstore/common/rpc/config.go
  blobstore/common/rpc/context_test.go
  blobstore/common/rpc/lb.go
  blobstore/common/rpc/simple.go
  blobstore/common/rpc/simple_test.go
Labels: WILL FIX, component/blobstore/rpc

#1747 docs(docs-zh): add create volume demo and faq
  docs-zh/source/design/authnode.md
  docs-zh/source/design/client.md
  docs-zh/source/faq/development.md
  docs-zh/source/index.rst
  docs-zh/source/maintenance/admin-api/master/user.md
  docs-zh/source/maintenance/admin-api/master/user.rst
  docs-zh/source/maintenance/admin-api/master/volume.md
  docs-zh/source/maintenance/admin-api/master/volume.rst
  docs-zh/source/user-guide/coldvol.md
  docs-zh/source/user-guide/volume.md
Labels: documentation

#1748 docs(docs-zh): add config usage and format docs
  docs-zh/source/cli/cli.rst
  docs-zh/source/deploy/k8s.md
  docs-zh/source/deploy/manual-deploy.md
  docs-zh/source/deploy/manual-deploy.rst
  docs-zh/source/deploy/yum.rst
  docs-zh/source/index.rst
  docs-zh/source/maintenance/configs/datanode.md
  docs-zh/source/maintenance/configs/master.md
  docs-zh/source/maintenance/configs/metanode.md
  docs-zh/source/maintenance/configs/objectnode.md
  docs-zh/source/maintenance/configs/scheduler.md
  docs-zh/source/maintenance/diskerr.md
  docs-zh/source/maintenance/diskerr.rst
  docs-zh/source/maintenance/env.md
  docs-zh/source/maintenance/env.rst
  docs-zh/source/maintenance/svrconf.rst
  docs-zh/source/maintenance/tool.rst
  docs-zh/source/maintenance/tools/blobstore.md
  docs-zh/source/maintenance/tools/cli.md
  docs-zh/source/overview/introduction.md
  docs-zh/source/user-guide/k8s.md
Labels: documentation

#1749 docs(docs-zh): improve k8s deployment documents
  docs-zh/source/deploy/k8s.md
Labels: documentation

#1768 docs(docs-zh): add config of blobstore's access
  docs-zh/source/maintenance/configs/blobstore/access.md
Labels: documentation

#1809 docs(docs-zh): add fuse usage
  docs-zh/source/faq/fuse.md
  docs-zh/source/index.rst
  docs-zh/source/sidebarConfig.js
  docs-zh/source/user-guide/fuse.md
Labels: documentation

#1811 docs(docs-zh): add clustermgr disk manage order
  docs-zh/source/maintenance/admin-api/blobstore/clustermgr.md
Labels: documentation

#1796 docs(docs-zh): add service failure recovery documentation for blobstore
  docs-zh/source/faq/build.md
  docs-zh/source/maintenance/admin-api/blobstore/cm.md
  docs-zh/source/maintenance/diskerr.md
  docs-zh/source/maintenance/svrconf.rst
  docs-zh/source/sidebarConfig.js
  docs-zh/source/user-guide/blobstore.md
  docs-zh/source/version.json
  docs-zh/version.json
Labels: documentation, component/blobstore

#1815 docs(docs-zh): optimize document title
  docs-zh/source/maintenance/admin-api/blobstore/access.md
  docs-zh/source/maintenance/admin-api/blobstore/base.md
  docs-zh/source/maintenance/admin-api/blobstore/blobnode.md
  docs-zh/source/maintenance/admin-api/blobstore/cm.md
  docs-zh/source/maintenance/admin-api/blobstore/scheduler.md
  docs-zh/source/maintenance/admin-api/master/cluster.md
  docs-zh/source/maintenance/admin-api/master/data-partition.md
  docs-zh/source/maintenance/admin-api/master/datanode.md
  docs-zh/source/maintenance/admin-api/master/failureDomain.md
  docs-zh/source/maintenance/admin-api/master/management.md
  docs-zh/source/maintenance/admin-api/master/meta-partition.md
  docs-zh/source/maintenance/admin-api/master/metanode.md
  docs-zh/source/maintenance/admin-api/master/user.md
  docs-zh/source/maintenance/admin-api/master/volume.md
  docs-zh/source/maintenance/admin-api/metanode/dentry.md
  docs-zh/source/maintenance/admin-api/metanode/inode.md
  docs-zh/source/maintenance/admin-api/metanode/partition.md
Labels: documentation

#1831 docs(docs-zh): update the picture of official accounts
  docs-zh/source/community/overview.md
  docs-zh/source/community/pic/qrcode.bmp
  docs-zh/source/community/pic/qrcode.png
  docs-zh/source/user-guide/blobstore.md
Labels: documentation

#1840 docs(docs-zh): fix document formatting
  docs-zh/source/design/blobstore.md
  docs-zh/source/design/master.md
  docs-zh/source/faq/build.md
  docs-zh/source/maintenance/administration.rst
  docs-zh/source/maintenance/env.md
  docs-zh/source/maintenance/log.md
  docs-zh/source/maintenance/metrics.rst
  docs-zh/source/maintenance/svrconf.rst
  docs-zh/source/sidebarConfig.js
Labels: documentation

#1834 feat(blobstore): add dump snapshot tool for clustermgr of blobstore at cli
  blobstore/cli/clustermgr/backup.go
  blobstore/cli/clustermgr/clustermgr.go
Labels: component/blobstore/cli

#1849 docs(docs-zh): format the document
  docs-zh/source/deploy/node.md
  docs-zh/source/deploy/requirement.md
  docs-zh/source/deploy/verify.md
  docs-zh/source/deploy/yum.md
  docs-zh/source/evaluation/env.md
  docs-zh/source/maintenance/admin-api/master/user.md
  docs-zh/source/maintenance/admin-api/master/volume.md
  docs-zh/source/maintenance/configs/blobstore/access.md
  docs-zh/source/maintenance/configs/blobstore/blobnode.md
  docs-zh/source/maintenance/configs/blobstore/cm.md
  docs-zh/source/maintenance/configs/blobstore/proxy.md
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs-zh/source/maintenance/configs/datanode.md
  docs-zh/source/maintenance/configs/master.md
  docs-zh/source/maintenance/configs/metanode.md
  docs-zh/source/maintenance/configs/objectnode.md
  docs-zh/source/maintenance/tool.md
  docs-zh/source/user-guide/file.md
  docs-zh/source/user-guide/volume.md
Labels: documentation

#1852 feat(blobstore): add raft db tools for clustermgr in cli
  blobstore/cli/clustermgr/clustermgr.go
  blobstore/cli/clustermgr/raftdb.go
Labels: component/blobstore/cli

#1853 chore(docs-zh): update blobstore access and proxy document
  docs-zh/source/maintenance/configs/blobstore/access.md
  docs-zh/source/maintenance/configs/blobstore/proxy.md
  docs-zh/source/maintenance/configs/blobstore/rpc.md
  docs-zh/source/maintenance/metrics/metrics.md
Labels: documentation

#1859 docs(docs-zh): fix leader stats path of scheduler
  docs-zh/source/maintenance/admin-api/blobstore/scheduler.md
Labels: documentation

#1872 docs(docs-zh): update the design doc of datanode
  docs-zh/source/design/datanode.md
  docs-zh/source/pic/cfs-data-largefile.png
  docs-zh/source/pic/cfs-data-smallfile.png
  docs-zh/source/pic/cfs-data-storage-topology.png
Labels: documentation

#1676 [Enhancement] automatically add data replica for data partitions which lack replica
  master/api_service.go
  master/cluster.go
  master/data_partition.go
  master/http_server.go
  master/metadata_fsm_op.go
  proto/admin_proto.go
Labels: discuss

#1666 [Enhancement] Remove some redundant code
  storage/extent.go
Labels: discuss

#1674 [Enhancemant] Support fuse request timeout, add client metrics
  client/fuse.go
  depends/bazil.org/fuse/examples/clockfs/clockfs.go
  depends/bazil.org/fuse/examples/hellofs/hello.go
  depends/bazil.org/fuse/fs/fstestutil/mounted.go
  depends/bazil.org/fuse/fs/serve.go
  depends/bazil.org/fuse/fuse.go
  depends/bazil.org/fuse/options.go
  proto/mount_options.go
Labels: discuss
