Repository cubefs/cubefs, pull requests merged in 2023-04, with the labels that each got.

#1675 [Enhancement] add check if vol has available space before create data partition
  master/api_service.go
  master/cluster.go
  master/vol.go
  proto/errors.go
Labels: discuss

#1806 chore: migrate from k8s.gcr.io to registry.k8s.io
  docs-zh/source/user-guide/k8s.md
Labels: documentation

#1890 chore(ci): fixup ci checks with gofmt
  .github/workflows/ci.yml
Labels: bug

#1889 add blobnode chunk dump tools
  blobstore/cli/blobnode/chunk.go
  blobstore/cli/blobnode/chunk_data.go
  blobstore/cli/blobnode/chunk_meta.go
Labels: component/blobstore/cli

#1929 docs: add articles
  docs-zh/source/community/article.md
  docs/source/community/article.md
Labels: documentation

#1934 fix(access): getting next shard when connection refused of blobnode
  blobstore/access/stream_get.go
Labels: component/blobstore

#1942 docs: update the development guide
  docs-zh/source/community/overview.md
  docs/source/community/overview.md
Labels: documentation
