Repository cubefs/cubefs, pull requests merged in 2023-06, with the labels that each got.

#2052 enhance: only deleted volume be ignored when do dps cache transfer
  master/cluster.go
  master/http_server.go
  master/metadata_fsm_op.go
Labels: bug, component/master

#2061 docs(config): update docs for supporting consumer group
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs/source/maintenance/configs/blobstore/scheduler.md
Labels: documentation

#2069 docs(docs,docs-zh): update config documentation for proxy of blobstore
  docs-zh/source/maintenance/configs/blobstore/proxy.md
  docs/source/maintenance/configs/blobstore/proxy.md
Labels: documentation

#2035 test(datanode): fix limit_test.go unit test
  datanode/limit_test.go
Labels: activites

#2071 feat(docs): optimize illustrations for documents in Zone Management
  docs-zh/source/pic/nodeset.png
  docs/source/pic/nodeset.png
Labels: documentation

#2074 docs(config): add commit_interval_ms for scheduler
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs/source/maintenance/configs/blobstore/scheduler.md
Labels: documentation

#2076 fix(master): mps dead lock may cause master cann't accept request for…
  master/vol.go
Labels: bug, component/master

#2063 docs: Fix missing closing parenthesis in design document
  docs-zh/source/design/metanode.md
Labels: documentation

#2078 docs(config): add punishment docs for blob delete and shard repair
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs/source/maintenance/configs/blobstore/scheduler.md
Labels: documentation

#2096 test(metanode): add txid_allocator.go unit test
  metanode/txid_allocator_test.go
Labels: activites

#2098 test(objectnode): add auth.go unit test
  objectnode/auth_test.go
Labels: activites

#2105 fix(cli,client,master,sdk): 1.add ability to force reset transaction …
  cli/cmd/const.go
  cli/cmd/fmt.go
  cli/cmd/vol.go
  client/fs/super.go
  client/fuse.go
  master/api_args_parse.go
  master/api_service.go
  master/cluster.go
  master/const.go
  master/metadata_fsm_op.go
  master/vol.go
  proto/admin_proto.go
  proto/mount_options.go
  proto/transaction.go
  sdk/master/api_admin.go
  sdk/meta/meta.go
  sdk/meta/operation.go
Labels: bug, component/master, component/cli, component/client

#2095 test(datanode): add stat.go unit test
  datanode/stat_test.go
Labels: activites

#2111 fix(objectnode): bucket metadata cache synchronization
  objectnode/api_middleware.go
  objectnode/cors_handler.go
  objectnode/fs_volume.go
  objectnode/fs_volume_meta.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
Labels: bug

#2113 fix(cli,master): set default transaction value for old volume from pr…
  cli/cmd/vol.go
  master/vol.go
Labels: bug, component/master, component/cli

#2110 fix(client): randomwrite request should not be limited by uid and dir…
  client/fs/file.go
  libsdk/libsdk.go
  objectnode/fs_volume.go
  preload/sdk/preloadsdk.go
  sdk/data/blobstore/reader.go
  sdk/data/blobstore/reader_test.go
  sdk/data/blobstore/writer.go
  sdk/data/stream/extent_client.go
  sdk/data/stream/stream_writer.go
Labels: component/client

#2123 fix(master): fix api_service_test.go
  master/api_service_test.go
  master/meta_node_test.go
Labels: activites

#2129 fix(proxy): fix the issue of volume capacity statistics failure
  blobstore/proxy/allocator/volume.go
  blobstore/proxy/allocator/volumemgr.go
  blobstore/proxy/allocator/volumemgr_test.go
Labels: bug, component/blobstore

#2124 [Feature]: Master does snapshot optimization
  master/master_manager_test.go
  master/metadata_fsm.go
  master/server.go
  raftstore/store_rocksdb.go
  util/fileutil/exists.go
  util/fileutil/exists_test.go
Labels: activites

#2141 docs(scheduler): perfect configuration example
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs/source/maintenance/configs/blobstore/scheduler.md
Labels: documentation

#2142 cleanup(datanode): storage/extent.go
  storage/extent.go
Labels: first good pr

#2114 feat: support the master to uniformly configure the push gateway address of the data reported by the client
  client/fuse.go
  master/api_service.go
  master/cluster.go
  master/config.go
  master/http_server.go
  master/server.go
  proto/admin_proto.go
  sdk/master/api_admin.go
Labels: activites

#2174 fix(blobnode): modify camel case
  blobstore/api/blobnode/iostat.go
  blobstore/api/blobnode/iostat_test.go
  blobstore/blobnode/base/flow/iostat.go
  blobstore/blobnode/core/chunk/compact.go
  blobstore/blobnode/core/disk/chunkinspect.go
  blobstore/blobnode/core/disk/disk.go
  blobstore/blobnode/core/storage/datafile.go
  blobstore/blobnode/datainspect.go
  blobstore/blobnode/db/metadb.go
  blobstore/blobnode/shard.go
Labels: component/blobstore
