Repository cubefs/cubefs, pull requests merged in 2023-05, with the labels that each got.

#1943 [Feature]: support showing migrating process
  blobstore/cli/scheduler/migrate.go
  blobstore/common/errors/scheduler.go
Labels: component/blobstore/cli

#1862 Feature: add ClusterUUID for mn/dn to identify a cluster upon restart
  datanode/partition_raft.go
  datanode/server.go
  datanode/server_handler.go
  master/api_service.go
  master/cluster.go
  master/http_server.go
  master/metadata_fsm_op.go
  metanode/api_handler.go
  metanode/metanode.go
  metanode/raft_server.go
  proto/admin_proto.go
  util/config/config.go
Labels: discuss

#1965 doc(fix): fix typo in Kubernetes deployment
  docs-zh/source/deploy/k8s.md
  docs/source/deploy/k8s.md
Labels: documentation

#1968 docs(deploy): correcting deployment dependency instructions
  docs-zh/source/deploy/requirement.md
  docs-zh/source/user-guide/blobstore.md
  docs/source/deploy/requirement.md
  docs/source/user-guide/blobstore.md
  util/buf/bcache_pool.go
Labels: documentation

#2001 chore(docs): change v3.2.2 to v3.3.0
  docs-zh/source/maintenance/admin-api/blobstore/scheduler.md
  docs-zh/source/maintenance/configs/blobstore/proxy.md
  docs-zh/source/maintenance/configs/blobstore/scheduler.md
  docs/source/maintenance/admin-api/blobstore/scheduler.md
  docs/source/maintenance/configs/blobstore/proxy.md
  docs/source/maintenance/configs/blobstore/scheduler.md
Labels: documentation

#2003 Update CHANGELOG.md
  CHANGELOG.md
Labels: first good pr

#2015 feat(cfs-cli): cfs-cli cluster info supports displaying all master in…
  cli/cmd/fmt.go
  master/api_service.go
  master/cluster.go
  proto/model.go
Labels: activites
